### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by jswift** [kronosking007/mmdb-challenge#1]
After running npm start, I get a "Failed to compile" error

![image](https://user-images.githubusercontent.com/641652/122840232-dcbdfd00-d338-11eb-806e-f9a15f574492.png)

> ./src/components/Header/Header.js
Module not found: Can't resolve './Filters/Filters' in '/home/jarrod.swift/employment/code-challenges/aditya-nath-omdb/my-moviedb/src/components/Header'

Steps: 
1. `npm install`
2. `npm start`

Versions:
- OS: Ubuntu 20.04.02
- Node: 16.2.0
- NPM: 7.13.0
-

**Comment by kronosking007** [comment]
Found the problem. Looks Like the renaming of files is not reflected in the repo after commits. Fixing this now.

**Comment by kronosking007** [comment]
Created new project repo with the proper naming convention. Please find it here: https://github.com/kronosking007/moviedb-challenge

**Comment by kronosking007** [comment]
This repo is obsolete starting 22 June 2021.

**Comment by kronosking007** [comment]
Closing Issue

**Comment by kronosking007** [comment]
Hi Jarrod,

Good Afternoon.
I apologize for my delayed response, I was up all night fixing bugs.
I just got to check your mail.

I have fixed the Issue now.

*Reason for Error: *
 Looks Like the renaming of files in my local project folder, is not
reflected in the GitHub repo even after several commits.

*Solution:*
Created a new project repository with the proper naming convention.
Please find the updated project folder here:
https://github.com/kronosking007/moviedb-challenge  (working-tested)

I have also closed the open Issue in the old project repo.

Thank you for your feedback.

Best Regards
Aditya Nath
